pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }

    environment {
        cluster = 'vproprod'
        service = 'vproAppProdSVC'
    }

    stages {
        stage('Deploy to ECS Prod') {
            steps {
                withAWS(credentials: 'awscreds', region: 'ap-southeast-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
}