name: Hprofile Actions
on: workflow_dispatch #Manual workflow
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test
      
      - name: Run Checkstyle
        run: mvn checkstyle:checkstyle
    
